### ISSUE TITLE
non fastq file

### ISSUE THREAD

**Issue by aedin** [brocklab/pycashier#2]
Hi
I am getting the following error ;

ERROR! There is a non fastq file in the provided fastq directory: sample_R1.fastq.gz
Exiting.

This seems to be coming from cashier.py 

  for f in fastqs:
        ext = os.path.splitext(f)[-1].lower()
        if ext != '.fastq':
            print('ERROR! There is a non fastq file in the provided fastq directory: {}'.format(f))
            print('Exiting.')

Please recommend the file formatting/naming

**Comment by daylinmorgan** [comment]
Currently, the file format depends on the operation being performed. 

For barcode extraction/clustering `cashier ./fastqs` 
It expects a directory with uncompressed fastqs. 

For merging of overlapping reads `cashier -m ./fastqs` 
It expects 2 compressed (sample1._R1.fastq.gz, sample1._R2.fastq.gz) fastqs for each sample.

Since the software currently relies on my naming conventions I will update the README and error prompts with naming format requirements. 

Also, note that it expects sample names to be delimited with a period. 

`sample1.raw.fastq
sample2._R1.fastq.gz`

**Comment by aedin** [comment]
Hi 
Our sequencing is from the Broad Institute facility.  This is a description of their output files ;


Every run will have un-demultiplexed FastQs for each lane – one for each template and barcode read. A paired-end read with two barcodes will have the following files:
- [FLOWCELL].[LANE].1.fastq (FastQ for the first template read)
- [FLOWCELL].[LANE].barcode_1.fastq (FastQ for the first barcode read)
- [FLOWCELL].[LANE].barcode_2.fastq (FastQ for the second barcode read)
- [FLOWCELL].[LANE].2.fastq (FastQ for the second template read)

(eg 2_HVJJ2BGXF.2.barcode_1.fastq.gz)

Read names in these files will look like this: @SL-NXA:12345AGXX140711:12345AGXX:1:11101:10000:10323 1:Y:0: Note that they do not include the barcode as part of the read name.

Runs that have requested demultiplexing and all runs for which Picard processing is requested will also have demultiplexed FastQs for every expected barcode in the lane:

- [FLOWCELL].[LANE].TCCTGAGC_TCTACTCT.unmapped.1.fastq (FastQ for the first template read for all reads associated with barcode TCCTGAGC_TCTACTCT)
- [FLOWCELL].[LANE].1.TCCTGAGC_TCTACTCT.unmapped.barcode_1.fastq (FastQ for the first barcode read for all reads associated with barcode TCCTGAGC_TCTACTCT)
- [FLOWCELL].[LANE].1.TCCTGAGC_TCTACTCT.unmapped.barcode_2.fastq (FastQ for the second barcode read for all reads associated with barcode TCCTGAGC_TCTACTCT)
- [FLOWCELL].[LANE].1.TCCTGAGC_TCTACTCT.unmapped.2.fastq (FastQ for the second template read for all reads associated with barcode TCCTGAGC_TCTACTCT)


(eg 2_HVJJ2BGXF.2.CCACTCGT.unmapped.1.fastq.gz)

Reads that did not match any of the expected barcodes will be in files named as follows:

- [FLOWCELL].[LANE].1.unmatched.1.fastq (FastQ for the first template read for all reads not associated with any expected barcode)
- [FLOWCELL].[LANE].1.unmatched.barcode_1.fastq (FastQ for the first barcode read for all reads not associated with any expected barcode)
- [FLOWCELL].[LANE].1.unmatched.barcode_2.fastq (FastQ for the second barcode read for all reads not associated with any expected barcode)
- [FLOWCELL].[LANE].1.unmatched.2.fastq (FastQ for the second template read for all reads not associated with any expected barcode) Read names in the demultiplexed FastQs will look like this: @SL-NXA:H0RVWAGXX140711:H0RVWAGXX:1:11101:10002:3013 :Y:0:TCCTGAGCTCTACTCTTCTACTCT

Note that the expected barcode to which the read was matched is part of the read name in these files. This is not the actual sequence from the barcode read, merely an indicator of the barcode to which the read was matched.


For runs that request Picard processing, BAM files and metrics files are also provided.

**Comment by aedin** [comment]
Given the above, do you recommend, renaming files to your scheme, or amending the code?

**Comment by daylinmorgan** [comment]
If I understand correctly these files contain the actual reads for a given set of indices. 

- [FLOWCELL].[LANE].TCCTGAGC_TCTACTCT.unmapped.1.fastq (FastQ for the first template read for all reads associated with barcode TCCTGAGC_TCTACTCT)
- [FLOWCELL].[LANE].1.TCCTGAGC_TCTACTCT.unmapped.2.fastq (FastQ for the second template read for all reads associated with barcode TCCTGAGC_TCTACTCT)

You will always need to demultiplex your files prior to using cashier. 

It would be simplest to rename each of these either with their index as they already are such as:
`TCCTGAGC_TCTACTCT.unmapped._R1.fastq
TCCTGAGC_TCTACTCT.unmapped._R2.fastq`

Or with a more informative sample title. (e.g. `sampleY._R1.fastq`) This is up to your preference of course. 
Currently it expects PE reads to be compressed if you are attempting to merge them. Though I will update it to accept either compressed or uncompressed fastqs for merging reads.

**Comment by aedin** [comment]
Thanks , if I use your naming scheme, it seems to run.  I get the "Processing for sample1 complete!" however the .tsv file in outs is null.  Where are the results output.  What are the files in pipelne and outs

**Comment by daylinmorgan** [comment]
A typical run with 2 files would look like this:
```
├── outs
│   ├── sample1.barcodes.r3d1.min10.tsv 
│   └── sample2.barcodes.r3d1.min10.tsv        
├── pipeline
│   ├── sample1.barcode.q30.fastq      
│   ├── sample1.barcodes.q30.c2.tsv   
│   ├── sample1.barcodes.q30.tsv   
│   ├── sample1.barcodes.r3d1.tsv  
│   ├── sample2.barcode.q30.fastq
│   ├── sample2.barcodes.q30.c2.tsv 
│   ├── sample2.barcodes.q30.tsv 
│   └── sample2.barcodes.r3d1.tsv
└── rawfastqs
      ├── sample1.fastq
      └── sample2.raw.fastq
3 directories, 12 files  
```

For each sample there are some intermediary files generated. 

Following extraction PHRED quality filtering: 
- `sample1.barcode.q30.fastq` 
- `sample1.barcodes.q30.tsv`

Following clustering:
- `sample1.barcodes.q30.c2.tsv`
- `sample1.barcodes.r3d1.tsv`

Following minimum read filtering:
- `sample1.barcodes.r2d1.min10.tsv`

This last file should contain two columns, your extracted sequences and their abundance following message passing clustering.

If these are empty it likely means that extraction failed.  
What parameters are you passing to cashier? Which of files in `pipeline` are empty?
